### ISSUE TITLE
JOSS: MPFR assertion failed

### ISSUE THREAD

**Issue by vissarion** [AngryMaciek/hypercomplex#36]
The following code
```
#include "hypercomplex/Hypercomplex.hpp"

int main(void){

  mpfr_t A[8];
  mpfr_init2(A[0], get_mpfr_precision());
  mpfr_init2(A[1], get_mpfr_precision());
  mpfr_init2(A[2], get_mpfr_precision());
  mpfr_init2(A[3], get_mpfr_precision());
  mpfr_init2(A[4], get_mpfr_precision());
  mpfr_init2(A[5], get_mpfr_precision());
  mpfr_init2(A[6], get_mpfr_precision());
  mpfr_init2(A[7], get_mpfr_precision());
  mpfr_set_d(A[0], 1.5, MPFR_RNDN);
  mpfr_set_d(A[1], 2.5, MPFR_RNDN);
  mpfr_set_d(A[2], 0.0, MPFR_RNDN);
  mpfr_set_d(A[3], -1.5, MPFR_RNDN);
  mpfr_set_d(A[4], 0.5, MPFR_RNDN);
  mpfr_set_d(A[5], -0.5, MPFR_RNDN);
  mpfr_set_d(A[6], -0.5, MPFR_RNDN);
  mpfr_set_d(A[7], -1.5, MPFR_RNDN);

  Hypercomplex<mpfr_t, 8> Hx(A);

  std::cout << "Hx^30 = "; 
  mpfr_out_str(stdout, 10, 0, (Hx^30)[0], MPFR_RNDN);
  std::cout << std::endl;

  return 0;
}
```
compiled with `g++ --std=c++17 -lmpfr -lgmp ` (g++ version 12.2.0, mprf version 4.1.0) returns 
```
../../src/init2.c:52: MPFR assertion failed: ((p) >= 1 && (p) <= ((mpfr_prec_t) ((((mpfr_uprec_t) -1) >> 1) - 256)))
Aborted (core dumped)
```

This is part of my review for JOSS https://github.com/openjournals/joss-reviews/issues/5272

**Comment by AngryMaciek** [comment]
I have added the code you specified above [as a separate test case](https://github.com/AngryMaciek/hypercomplex/blob/09cf984ac30473e499a35d823649c79dfb10970b/.test/unit/test.cpp#L1263) on a new branch `revision`; please see the [ci logs](https://github.com/AngryMaciek/hypercomplex/actions/runs/4707559851/jobs/8349485974?pr=37#step:8:104).  
We get the same value as in the [docs](https://angrymaciek.github.io/hypercomplex/html/index.html).    
Unfortunately we cannot reproduce the error; could this be specific to your machine?

I found the following information on the internet:

> More specifically, the assertion checks that the precision parameter p is greater than or equal to 1 and less than or equal to a maximum value determined by the size of the data type used to store the precision. This maximum value is calculated based on the platform's mpfr_uprec_t type, which specifies the largest unsigned integer type available on the system. The 256 offset is added to ensure some additional safety margin.
>
> Therefore, the error message indicates that the program attempted to use an invalid precision value that is either too small (less than 1) or too large (exceeding the maximum precision that can be stored on the system).

**Comment by vissarion** [comment]
This is the info getting from `uname -a` 
```
Linux 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vissarion** [comment]
The same issue appear with clang++ 16. Note that the mpfr version in ci is 4.0.2 while in my local setting is 4.1.0, so this could be one explanation.

**Comment by AngryMaciek** [comment]
Are you sure you followed the exact installation instructions from the docs?

![Screenshot 2023-04-20 at 19 12 04](https://user-images.githubusercontent.com/19755308/233439673-235023ce-8c88-48d4-a9cb-11b6a32c318c.png)


On my personal mac machine I have a newer version and the tests pass too:

<img width="570" alt="Screenshot 2023-04-20 at 19 15 35" src="https://user-images.githubusercontent.com/19755308/233440283-958304fc-07c4-4f4c-a24b-64e329281494.png">

**Comment by vissarion** [comment]
OK, I found the issue, it seems that the above code is missing a `set_mpfr_precision()` statement. Then `get_mpfr_precision()` returns `0` and there is not enough precision to do the computation so mpfr assertion fails. In your test case most probably mpfr precision was set at some point before `get_mpfr_precision()` is executed and therefore the test was passing. I am closing this issue now.
